# Generated by .github/workflows/update.yml from the signed frc-mcp release. Do not edit.
cask "frc-mcp" do
  version "0.1.3"

  on_macos do
    on_arm do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "5b4a879f447290e93865569fd553d61dc9159b73d6b7dda3922e0754165ded8c"
    end
    on_intel do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "0dc17b5b048e68cd1e39e10b902b9961b4606572fefb474a26a94ccba32bc09f"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "27dae2c0f96c2ed4ce24d1361d35f09996bcbd0e3b634226cc844a24867f4e48"
    end
    on_intel do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "594a129aaef440b4e62798bb9cad91f2c4bc5f6c6ab12fe2b520ffb5b7214d2d"
    end
  end

  name "frc-mcp"
  desc "Version-correct FRC robotics software knowledge for coding agents (MCP server)"
  homepage "https://github.com/fikretyukselit/frc-mcp"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "frc-mcp"

  # Not notarized yet: clear the quarantine flag so Gatekeeper allows the first run.
  # The release itself is verified before this cask is written (cosign bundle).
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frc-mcp"]
    end
  end
end
