# Generated by .github/workflows/update.yml from the signed frc-mcp release. Do not edit.
cask "frc-mcp" do
  version "0.1.4"

  on_macos do
    on_arm do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_darwin_arm64.tar.gz"
      sha256 "054b38c4165a628169e5188d3ee8fbe2f7618e20a60e475a215042ea7cabe17c"
    end
    on_intel do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_darwin_amd64.tar.gz"
      sha256 "fd3a28893b4a7a014bb892f15b47d51396490751292329e45c5cc4aaffc18261"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_linux_arm64.tar.gz"
      sha256 "dd890dafebd38c34697019699c5004a643704033ca60a8e5a0c739c2ee6cfc31"
    end
    on_intel do
      url "https://github.com/fikretyukselit/frc-mcp/releases/download/v#{version}/frc-mcp_#{version}_linux_amd64.tar.gz"
      sha256 "0158402a3ebba6c8e25fd531ba2a7209e69dd196caf996bedf76834103f24cda"
    end
  end

  name "frc-mcp"
  desc "Version-correct FRC robotics software knowledge for coding agents (MCP server)"
  homepage "https://github.com/fikretyukselit/frc-mcp"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "frc-mcp"

  # Not notarized yet: clear the quarantine flag so Gatekeeper allows the first run.
  # The release itself is verified before this cask is written (cosign bundle).
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/frc-mcp"]
    end
  end
end
