#!/usr/bin/env python3
"""Write Casks/frc-mcp.rb for a release from its (verified) checksums.txt.

usage: cask.py VERSION CHECKSUMS_TXT
"""
import re
import sys

REPO = "https://github.com/fikretyukselit/frc-mcp"


def main() -> None:
    version, checksums = sys.argv[1], sys.argv[2]
    if not re.fullmatch(r"\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?", version):
        sys.exit(f"bad version {version!r}")
    sums = {}
    for line in open(checksums, encoding="utf-8"):
        h, name = line.split()
        sums[name] = h
    def sha(os_, arch):
        name = f"frc-mcp_{version}_{os_}_{arch}.tar.gz"
        if not re.fullmatch(r"[0-9a-f]{64}", sums.get(name, "")):
            sys.exit(f"no sha256 for {name}")
        return sums[name]
    url = REPO + '/releases/download/v#{version}/frc-mcp_#{version}_%s_%s.tar.gz'
    def block(os_, arch):
        return f'      url "{url % (os_, arch)}"\n      sha256 "{sha(os_, arch)}"'
    print(f'''# Generated by .github/workflows/update.yml from the signed frc-mcp release. Do not edit.
cask "frc-mcp" do
  version "{version}"

  on_macos do
    on_arm do
{block("darwin", "arm64")}
    end
    on_intel do
{block("darwin", "amd64")}
    end
  end
  on_linux do
    on_arm do
{block("linux", "arm64")}
    end
    on_intel do
{block("linux", "amd64")}
    end
  end

  name "frc-mcp"
  desc "Version-correct FRC robotics software knowledge for coding agents (MCP server)"
  homepage "{REPO}"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "frc-mcp"

  # Not notarized yet: clear the quarantine flag so Gatekeeper allows the first run.
  # The release itself is verified before this cask is written (cosign bundle).
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{{staged_path}}/frc-mcp"]
    end
  end
end''')


if __name__ == "__main__":
    main()
